# Generated by Django 5.2.8 on 2025-11-29 22:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
