# Generated by Django 5.2.8 on 2025-12-09 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('solucao', models.TextField(blank=True, null=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api_rest.lista')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('enunciado', models.TextField()),
                ('solucao', models.TextField(blank=True, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api_rest.questao')),
            ],
        ),
    ]
