# Generated by Django 5.2.8 on 2025-12-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_lista_questao_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='solucao',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='solucao',
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solucoes', to='api_rest.item')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucoes', to='api_rest.questao')),
            ],
        ),
    ]
