# Generated by Django 5.2.8 on 2025-12-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_remove_item_solucao_remove_questao_solucao_solucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='related_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='api_rest.questao'),
        ),
    ]
