# Generated by Django 5.2.8 on 2025-12-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_chatmessage_related_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='item',
            name='questao',
        ),
        migrations.RenameModel(
            old_name='Lista',
            new_name='Assignments',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='numero',
            new_name='number',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api_rest.assignments')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='question',
            field=models.ForeignKey(default='.', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api_rest.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='related_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='api_rest.question'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api_rest.item')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api_rest.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Solucao',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
