# Generated by Django 5.2.8 on 2026-02-01 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_remove_questao_lista_remove_item_questao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFromCSV',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('prova', models.IntegerField()),
                ('conteudo', models.IntegerField()),
                ('modelo', models.IntegerField()),
                ('versao', models.IntegerField()),
                ('dificuldade', models.FloatField()),
                ('materia', models.CharField(max_length=255)),
                ('enunciado', models.TextField()),
                ('solucao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prova', models.IntegerField()),
                ('dificuldade_media', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimuladoQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=255)),
                ('conteudo', models.IntegerField()),
                ('dificuldade', models.FloatField()),
                ('order', models.IntegerField()),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api_rest.simulado')),
            ],
        ),
    ]
