# Generated by Django 5.2.8 on 2026-02-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_questionfromcsv_simulado_simuladoquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='user',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='simulados', to='api_rest.user'),
            preserve_default=False,
        ),
    ]
