# Generated by Django 5.2.8 on 2026-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_simulado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulado',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulado',
            name='tempo_segundos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simuladoquestion',
            name='resposta_usuario',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
