# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_simulado_concluido_simulado_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfromcsv',
            name='alternativas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
