# Generated by Django 5.2.8 on 2026-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_questionfromcsv_alternativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfromcsv',
            name='gabarito',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
