# Generated by Django 5.2.8 on 2026-02-26 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_questionfromcsv_alternativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimuladoChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulado_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='api_rest.simuladoquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulado_chat_sessions', to='api_rest.user')),
            ],
        ),
        migrations.CreateModel(
            name='SimuladoChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_rest.simuladochatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='simuladochatsession',
            constraint=models.UniqueConstraint(fields=('user', 'simulado_question'), name='unique_user_simulado_question_chat'),
        ),
    ]
