# Generated by Django 5.2.8 on 2026-02-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_questionfromcsv_gabarito'),
        ('api_rest', '0011_simuladochatsession_simuladochatmessage_and_more'),
    ]

    operations = [
    ]
